version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  labels:
  - skip-changelog
  - dependencies
  versioning-strategy: increase
  ignore:
  - dependency-name: "@babel/cli"
    versions:
    - "> 7.12.10, < 7.13"
  - dependency-name: "@babel/core"
    versions:
    - "> 7.12.10, < 7.13"
  - dependency-name: "@babel/preset-env"
    versions:
    - "> 7.12.11, < 7.13"
  - dependency-name: "@babel/register"
    versions:
    - "> 7.12.10, < 7.13"
  - dependency-name: eslint
    versions:
    - "> 7.12.0, < 7.13"
  - dependency-name: eslint
    versions:
    - "> 7.3.0, < 7.4"
  - dependency-name: eslint-plugin-jest
    versions:
    - "> 24.0.0, < 24.1"
  - dependency-name: jest
    versions:
    - ">= 25.a, < 26"
  - dependency-name: prettier
    versions:
    - "> 2.1.1, < 2.2"
  - dependency-name: sinon
    versions:
    - "> 9.2.3, < 9.3"
  - dependency-name: uglify-js
    versions:
    - "> 3.11.0, < 3.12"
  - dependency-name: uglify-js
    versions:
    - "> 3.12.4, < 3.13"
  - dependency-name: webpack
    versions:
    - "> 4.44.1, < 4.45"
  rebase-strategy: disabled
